"""add created_at and align constraints after refactor

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-14 10:23:51.225105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # reports.generated_at was renamed to created_at by the post-refactor models; carry the values over
    # before dropping the old column so existing report rows keep their real timestamp.
    op.add_column('reports', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.execute('UPDATE reports SET created_at = generated_at')
    op.drop_column('reports', 'generated_at')
    op.add_column('study_predictions', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint(op.f('uq_studypred_study_task'), 'study_predictions', type_='unique')
    op.create_unique_constraint('uq_study_predictions_study_task', 'study_predictions', ['study_id', 'task_name'])
    op.add_column('video_labels', sa.Column('task_type', sa.Text(), nullable=True))
    op.add_column('video_labels', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('video_labels', 'value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_constraint(op.f('uq_videolabel_video_task'), 'video_labels', type_='unique')
    op.create_index('ix_video_labels_task_name', 'video_labels', ['task_name'], unique=False)
    op.create_unique_constraint('uq_video_labels_video_task', 'video_labels', ['video_id', 'task_name'])
    op.add_column('video_predictions', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint(op.f('uq_videopred_video_task'), 'video_predictions', type_='unique')
    op.create_index('ix_video_predictions_task_name', 'video_predictions', ['task_name'], unique=False)
    op.create_unique_constraint('uq_video_predictions_video_task', 'video_predictions', ['video_id', 'task_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_video_predictions_video_task', 'video_predictions', type_='unique')
    op.drop_index('ix_video_predictions_task_name', table_name='video_predictions')
    op.create_unique_constraint(op.f('uq_videopred_video_task'), 'video_predictions', ['video_id', 'task_name'], postgresql_nulls_not_distinct=False)
    op.drop_column('video_predictions', 'created_at')
    op.drop_constraint('uq_video_labels_video_task', 'video_labels', type_='unique')
    op.drop_index('ix_video_labels_task_name', table_name='video_labels')
    op.create_unique_constraint(op.f('uq_videolabel_video_task'), 'video_labels', ['video_id', 'task_name'], postgresql_nulls_not_distinct=False)
    op.alter_column('video_labels', 'value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('video_labels', 'created_at')
    op.drop_column('video_labels', 'task_type')
    op.drop_constraint('uq_study_predictions_study_task', 'study_predictions', type_='unique')
    op.create_unique_constraint(op.f('uq_studypred_study_task'), 'study_predictions', ['study_id', 'task_name'], postgresql_nulls_not_distinct=False)
    op.drop_column('study_predictions', 'created_at')
    op.add_column('reports', sa.Column('generated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('reports', 'created_at')
    # ### end Alembic commands ###
